pandas package - Exploratory Data Analysis

Preprocessing - clean, missing data, wrong data,

In [1]:
# Program 1: Simple Decision Tree Classification
 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# Small dataset
data = {
    'Hours_Studied': [1,2,3,4,5,6,7,8],
    'Pass': [0,0,0,1,1,1,1,1]
}

In [4]:
print(data)

{'Hours_Studied': [1, 2, 3, 4, 5, 6, 7, 8], 'Pass': [0, 0, 0, 1, 1, 1, 1, 1]}

In [3]:
df = pd.DataFrame(data)

In [5]:
X = df[['Hours_Studied']]
y = df['Pass']

In [9]:
print(X)
print(y)

   Hours_Studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
Name: Pass, dtype: int64

In [10]:

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42)

In [11]:
# Decision Tree Model
model = DecisionTreeClassifier(max_depth=2, random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2, random_state=42)

In [12]:
# Prediction
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0

In [1]:
#!pip install matplotlib

Requirement already satisfied: matplotlib in c:\python312\lib\site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\python312\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\python312\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\python312\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\python312\lib\site-packages (from matplotlib) (2.4.0)
Requirement already satisfied: packaging>=20.0 in c:\python312\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\python312\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\python312\lib\site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\python312\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.0
[notice] To update, run: C:\Python312\python.exe -m pip install --upgrade pip

In [2]:
#!{sys.executable} -m pip install matplotlib

'{sys.executable}' is not recognized as an internal or external command,
operable program or batch file.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#from google.colab import files
#data=files.upload()

In [3]:
#df_dia= pd.read_csv('diabetes.csv')
df_dia=pd.read_csv("diabetes.csv")

#dataframe,--
#series-single col

BMI	- Body Mass Index

DiabetesPedigreeFunction	- heredity factor - chances of getting diabetes because of parents

Outcome

1 Presence of diabetes

0 absence of diabetes

In [4]:
df_dia

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [11]:
df_dia.sample(n=5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
326,1,122,64,32,156,35.1,0.692,30,1
6,3,78,50,32,88,31.0,0.248,26,1
205,5,111,72,28,0,23.9,0.407,27,0
136,0,100,70,26,50,30.8,0.597,21,0
566,1,99,72,30,18,38.6,0.412,21,0

copy of dataset

In [8]:
df.head(n=10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [9]:
df.tail(n=10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [12]:
df=df_dia.copy()

In [15]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [16]:
df_dia

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

display first 5 rows

In [17]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

display first 30 patient details

In [18]:
df.head(30) # first 30 data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1
20,3,126,88,41,235,39.3,0.704,27,0
21,8,99,84,0,0,35.4,0.388,50,0
22,7,196,90,0,0,39.8,0.451,41,1
23,9,119,80,35,0,29.0,0.263,29,1
24,11,143,94,33,146,36.6,0.254,51,1
25,10,125,70,26,115,31.1,0.205,41,1
26,7,147,76,0,0,39.4,0.257,43,1
27,1,97,66,15,140,23.2,0.487,22,0
28,13,145,82,19,110,22.2,0.245,57,0
29,5,117,92,0,0,34.1,0.337,38,0

In [19]:
# first 50 data
df.head(50)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1
20,3,126,88,41,235,39.3,0.704,27,0
21,8,99,84,0,0,35.4,0.388,50,0
22,7,196,90,0,0,39.8,0.451,41,1
23,9,119,80,35,0,29.0,0.263,29,1
24,11,143,94,33,146,36.6,0.254,51,1
25,10,125,70,26,115,31.1,0.205,41,1
26,7,147,76,0,0,39.4,0.257,43,1
27,1,97,66,15,140,23.2,0.487,22,0
28,13,145,82,19,110,22.2,0.245,57,0
29,5,117,92,0,0,34.1,0.337,38,0
30,5,109,75,26,0,36.0,0.546,60,0
31,3,158,76,36,245,31.6,0.851,28,1
32,3,88,58,11,54,24.8,0.267,22,0
33,6,92,92,0,0,19.9,0.188,28,0
34,10,122,78,31,0,27.6,0.512,45,0
35,4,103,60,33,192,24.0,0.966,33,0
36,11,138,76,0,0,33.2,0.420,35,0
37,9,102,76,37,0,32.9,0.665,46,1
38,2,90,68,42,0,38.2,0.503,27,1
39,4,111,72,47,207,37.1,1.390,56,1
40,3,180,64,25,70,34.0,0.271,26,0
41,7,133,84,0,0,40.2,0.696,37,0
42,7,106,92,18,0,22.7,0.235,48,0
43,9,171,110,24,240,45.4,0.721,54,1
44,7,159,64,0,0,27.4,0.294,40,0
45,0,180,66,39,0,42.0,1.893,25,1
46,1,146,56,0,0,29.7,0.564,29,0
47,2,71,70,27,0,28.0,0.586,22,0
48,7,103,66,32,0,39.1,0.344,31,1
49,7,105,0,0,0,0.0,0.305,24,0

display last few records

In [ ]:
df.tail() # last 5 records

In [ ]:
df.tail(12)

In [20]:
# column headings
df.columns # not a function - it is a property

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='str')

In [ ]:
df.columns

In [21]:
df.shape # number of rows and columns

(768, 9)

In [22]:
df.size # number of data

6912

In [23]:
# multiply row x column
768*9

6912

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

Number of rows 768 index 0 to 767

Number of columns 9

There is no missing data

all data are numeric

data types int - float

In [25]:
# datatype
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [1]:
df_tit = pd.read_csv('Dataset/Titanic.csv')
df_tit

NameError: name 'pd' is not defined

In [ ]:
df_tit.info()

There are some missing data in titanic dataset

Remove cabin column as it has so much of missing data. it has
only 204 data out of 891

In [ ]:
df.columns # diabetes dataset

In [ ]:
df_tit=df_tit.drop(columns='Cabin',axis=1) # axis is 1 - column, 0- row

In [ ]:
df_tit.columns

In [ ]:
df_tit.info()

In [ ]:
# checking missing data
df_tit.isna().sum()

Feature ( column ) Engineering - Feature Selection - Feature Extraction

In [ ]:
df_tit.head()

In [ ]:
df_tit=df_tit.drop(columns=['Name','Ticket'],axis=1)

In [ ]:
df_tit.head()

In [ ]:
df_tit.isnull().sum()

Data Imputation - fill null values -

numeric - int, float - mean, median - average

string - object - mode -most repeated data

In [ ]:
# working with age column
df_tit['Age'].median()

In [ ]:
# filling missing data
df_tit['Age']=df_tit['Age'].fillna(df_tit['Age'].median())

In [ ]:
df_tit.isnull().sum() # missing data

In [ ]:
# filling missing data for Embarked column - string
df_tit['Embarked'].mode()

In [ ]:
df_tit['Embarked']=df_tit['Embarked'].fillna('S')

In [ ]:
df_tit.isnull().sum()

correlation - relationship betweeen variables

table - numeric data

values near to 1 . it has good positive correlation

values near to -1 it has good negative correlation

In [ ]:
df_tit.corr() # titanic data

In [ ]:
df.corr() # diabetics data

Glucose is highly correlated with outcome

Encoding Categorical Variables

Encoding - converting to numbers

In [ ]:
df_tit.head()

get dummies - converts strings ( objects ) to numeric

In [ ]:
df_tit.dtypes

In [ ]:
df_tit=pd.get_dummies(df_tit,columns=['Sex','Embarked'])
df_tit.head()

In [ ]:
df_tit.dtypes

In [ ]:
df_tit.corr()

In [ ]:
# dropping missing rows
df_tit.dropna()